@startuml
title Register a job  that a collaborator needs to have

skinparam classAttributeIconSize 0


class RegisterJobController {
    + RegisterJobController()
    + registerJob(jobName: String)

}

class RegisterJobUI {
    +main(args: String[]): void
}

class Repositories {
    RegisterJobRepository()
}
class RegisterJobView {
    displayForm() {
    }


class Collaborator {
    +String name
    +Date birthdate
    +Date admissionDate
    +address
    +phoneNumber
    +email
    +taxpayerNumber
    +identificationDocumentType
    +identificationDocumentNumber
}

RegisterJobUI ..> RegisterJobController: inputs wanted data
RegisterJobController ..> Repositories : inserts job in the repository
Collaborator ..> RegisterJobController : needs to have a collaborator
RegisterJobView ..> RegisterJobUI : displays
RegisterJobController ..> RegisterJobView : uses
@enduml