@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

 participant ":RegisterJobController" as RegisterJobController
 participant "Repositories" as Repositories
 participant ":RegisterJobRepository" as RegisterJobRepository

-> RegisterJobController : getjob()
group getjob
    activate RegisterJobController
    RegisterJobController -> Repositories: getRepository()
    activate Repositories
    Repositories -> RegisterJobController : RegisterJobRepository()
    deactivate Repositories
    RegisterJobController -> RegisterJobRepository: RegisterJobRepository()
    activate RegisterJobRepository
    RegisterJobRepository -> RegisterJobController : jobs
    deactivate RegisterJobRepository
    end
    <- RegisterJobController : jobs
    deactivate RegisterJobController


@enduml