@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "HRM" as USER
participant ":RegisterJobUI" as RegisterJobUI
participant ":RegisterJobController" as RegisterJobController
participant ":RegisterJobRepository" as RegisterJobRepository

activate USER
USER -> RegisterJobUI : asks to register a job
activate RegisterJobUI
RegisterJobUI ->USER : request job information
deactivate RegisterJobUI

USER -> RegisterJobUI : types requested job information
activate RegisterJobUI
RegisterJobUI -> RegisterJobController : Registers a new job
activate RegisterJobController
RegisterJobController -> RegisterJobRepository:inserts new job in the repository
activate RegisterJobRepository
RegisterJobRepository -> RegisterJobController : new job
deactivate RegisterJobRepository
RegisterJobController -> RegisterJobUI : new job
deactivate RegisterJobController

RegisterJobUI -> USER : Display operation Success
deactivate RegisterJobUI
deactivate USER

@enduml