@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources Manager" as HRM
participant ":GenerateTeamUI" as UI
participant ":GenerateTeamController" as CTRL
participant "skillRepository:\nSkillRepository" as SkillRepository
participant "selectedSkillsList:\nList<Skill>" as selectedSkillsList


activate HRM

        HRM -> UI : asks for a team proposal

        activate UI

            UI -> CTRL** : create

            UI --> HRM : asks for minimum and maximum team size

        deactivate UI

        HRM -> UI : enters minimum and maximum team size

        activate UI

            UI -> CTRL : getSkills()
            ref over CTRL
                Get Skill List

            end ref

            activate CTRL

            CTRL -> SkillRepository : createSelectedSkillsList()
            activate SkillRepository

            SkillRepository -> selectedSkillsList** : create()
            deactivate SkillRepository

                CTRL --> UI : skillList
            deactivate CTRL

            loop while continues

            UI --> HRM : shows skill list and asks to select one
        deactivate UI

    HRM -> UI : selects a skill
    activate UI

        UI -> CTRL : addSelectedSkillName(skillName)
        activate CTRL
            ref over CTRL
                Create Selected Skills List

            end ref

        deactivate CTRL

        UI --> HRM : asks to continue

    deactivate UI

    HRM -> UI : answers positively or negatively
    activate UI

            end loop

        UI -> CTRL : generateTeamProposal(minCollab, maxCollab)
        activate CTRL

            CTRL -> CTRL : getSelectedSkillsList()
            activate CTRL

            CTRL -> SkillRepository : getSelectedSkillsList()
            activate SkillRepository

            SkillRepository --> CTRL : selectedSkillsList
            deactivate SkillRepository

            CTRL --> CTRL : selectedSkillsList
            deactivate CTRL

            CTRL -> CTRL : createAvailableCollaboratorsList()

                ref over CTRL
                    Create Available Collaborators List

                end ref

                activate CTRL

                CTRL --> CTRL :
            deactivate CTRL

            CTRL -> CTRL : selectCollaboratorsForTeam(selectedSkillsList, minCollab, maxCollab)
            activate CTRL

                ref over CTRL
                    Generate Team Proposal

                end ref

                CTRL --> CTRL : teamProposal
            deactivate CTRL

            CTRL --> UI : teamProposal
        deactivate CTRL

        UI --> HRM : shows a team proposal
    deactivate UI

    HRM -> UI : accepts or refuses team proposal
    activate UI

        UI -> CTRL : registerTeam(teamProposal)
        activate CTRL

        ref over CTRL
            Register Team

        end ref

            CTRL --> UI : team

            deactivate CTRL
            UI --> HRM: displays operation result
    deactivate UI

deactivate HRM


@enduml