@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":GenerateTeamController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "collaboratorRepository:\nCollaboratorRepository" as CollaboratorRepository
participant "teamRepository:\nTeamRepository" as TeamRepository
participant "team\n:Team" as Team
participant "tempCollaboratorList:\nList<Collaborator>" as tempCollaboratorList

autonumber 19

    -> CTRL : createAvailableCollaboratorsList()
            autonumber 19.1
            group Create Available Collaborators List

            activate CTRL

CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getCollaboratorRepository()
                activate PLAT

                     PLAT --> CTRL: collaboratorRepository
            deactivate PLAT

            CTRL -> CollaboratorRepository : createTempCollaboratorList()
            activate CollaboratorRepository

                CollaboratorRepository -> tempCollaboratorList** : clone(collaboratorList)

                CollaboratorRepository --> CTRL : tempCollaboratorList

                deactivate CollaboratorRepository

                CTRL -> PLAT : getTeamRepository()
                activate PLAT

                    PLAT --> CTRL : teamRepository
                deactivate PLAT

            CTRL -> TeamRepository : removeUnavailableCollaborators(tempCollaboratorList)
                activate TeamRepository

                    loop for each team

                    TeamRepository -> Team: removeUnavailableCollaborators(tempCollaboratorList)
                    activate Team

                        loop for each collaborator of the team

                        Team -> tempCollaboratorList : remove(collaborator)
                        activate tempCollaboratorList

                        deactivate tempCollaboratorList

                        end loop

                    deactivate Team

                    end loop


                deactivate TeamRepository


                end group
                autonumber 20

            <-- CTRL :
            deactivate CTRL
@enduml