@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber 16

'hide footbox
participant ":GenerateTeamController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT

participant "collaboratorRepository:\nCollaboratorRepository" as CollaboratorRepository
participant "collaborator\n:Collaborator" as Collab


    -> CTRL : selectCollaboratorsForTeam(availableCollaborators, skills)
            activate CTRL
            autonumber 16.1
            group Choose Collaborators For Team

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getCollaboratorRepository()
                activate PLAT

                    PLAT --> CTRL: collaboratorRepository
                deactivate PLAT

                CTRL -> CollaboratorRepository : selectCollaboratorsForTeam(availableCollaborators, skills)
                activate CollaboratorRepository

                    loop for each available collaborator
                    CollaboratorRepository -> Collab : evaluateCollaborator(skills)
                    activate Collab

                        Collab --> CollaboratorRepository : evaluation
                    deactivate Collab

                    end loop

                    CollaboratorRepository --> CTRL : selectedCollaborators
                deactivate CollaboratorRepository

                end group
                autonumber 17

    <-- CTRL : selectedCollaborators
@enduml