@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber 5
'hide footbox

participant ":GenerateTeamController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillRepository:\nSkillRepository" as SkillRepository

 -> CTRL : getSkills()
            autonumber 5.1
            activate CTRL
            group Get Skill List

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getSkillRepository()
                activate PLAT

                    PLAT --> CTRL: skillRepository
                deactivate PLAT

                CTRL -> SkillRepository : getSkills()
                activate SkillRepository

                    SkillRepository --> CTRL : skillList
                deactivate SkillRepository

                end
                autonumber 8
                <-- CTRL : skillList
            deactivate CTRL


@enduml