@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US004

autonumber

actor "HRM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to assign one skill to a collaborator
    activate System

    System --> Employee : requests the name of the skill
    deactivate System

    Employee -> System : types skill's name
    activate System

    System --> Employee : shows all collaborator's skills and displays operation success
    deactivate System

deactivate Employee
@enduml