@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US 04

autonumber

actor "HRM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to assign one skill to a collaborator
    activate System

        System --> Employee : requests data
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : shows all collaborator's skills and displays operation success
    deactivate System

deactivate Employee
@enduml