@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model us002



class HRM {
}

class Job {
    Name

}
class Collaborator {
    name
    birthdate
    admissionDate
    address
    phoneNumber
    email
    taxpayerNumber
    identificationDocumentType
    identificationDocumentNumber
    }

HRM "1" -- "*" Job :registers>
Collaborator "*" - "1" Job : has >

@enduml