@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor yellow
}

title Use Case Diagram us002 - as a HRM I want to register a new job

left to right direction

rectangle "System Actor" as actor {
    actor "HRM" as HumanResourceManager
}


rectangle "Use Cases" as usecases{
    usecase "UC2 - Registers a new job" as UC2
    HumanResourceManager --> UC2
}

@enduml