@startuml
skinparam classAttributeIconSize 0

class RegisterSkillController {
    +registerSkill(name)
}


class RegisterSkillUI {
}
class Collaborator {
   -String name
   -Date birthdate
    -Date admissionDate
    -address
    phoneNumber
    email
    taxpayerNumber
    identificationDocumentType
    identificationDocumentNumber
}
RegisterSkillUI ..> RegisterSkillController
RegisterSkillController ..> Collaborator
@enduml