@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US 007

autonumber

actor "VFM" as VFM
participant ":System" as System


activate VFM

    VFM -> System: selects "register vehicle check-up" option
    activate System

         System --> VFM: request vehicle info
            deactivate System
                VFM -> System: enters vehicle info
                    activate System
                       System --> VFM: asks for validation of information
                                deactivate System
                                                VFM -> System: validates information
                                                    activate System
                                                                           System --> VFM: shows operation success
                                                                                    deactivate System
@enduml                   deactivate System
@enduml