@startuml
skinparam classAttributeIconSize 0

title US028 - Consult the tasks assigned to a Collaborator

class ConsultTasksUI {

}

class ConsultTasksController {
    + consultTasksController(taskRepository)
    + getEmailCollaborator()
    + List<GSTaskDTO> getTasks(email, startDate, endDate)
    + getStatusList()
    + consultTasksByStatus(tasksDTO)
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getGreenSpaceRepository()
    + getTaskRepository()
}

class Agenda {
    + getTasksByCollaborator(email)
    + getStatusList()
    + toDTO(tasks)
    + consultTasksByStatus(tasksDTO, status)
    + consultTasks(tasksDTO)
}

class GSTaskMapper {
    + List<TGSaskDTO> toDTO(List<GSTask> tasks)
    + GSTaskDTO toDTO(GSTask task)
}

class GSTaskDTO {
    title
    description
    degreeOfUrgency
    expectedDuration
    status
    startingDate
}

class GSTask {
    title
    description
    degreeOfUrgency
    expectedDuration
    status
    startingDate
}

ConsultTasksUI ..> ConsultTasksController
ConsultTasksController ..> Repositories : repositories
ConsultTasksController ..> Agenda : taskRepository
Repositories ---> "1" Agenda: taskRepository
Agenda --> GSTask: tasks

Agenda ..> GSTaskMapper
GSTaskMapper ..> GSTaskDTO
GSTaskMapper ..> GSTask
@enduml