@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":ConsultTasksController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "agenda\n:Agenda" as Agenda
participant "taskMapper\n:GSTaskMapper" as TaskMapper
participant "task\n:GSTask" as Task
participant "tasksList\n:List<GSTask>" as TasksList
participant "tasksList\n:List<GSTaskDTO>" as TasksListDTO
participant "taskDTO\n:GSTaskDTO" as TaskDTO

autonumber 34
-> CTRL : getTasks(teamsDTO, startDate, endDate)

autonumber 34.1

activate CTRL
    group Get Tasks By Date Range
           CTRL -> Agenda : getTasks(teamsDTO, startDate, endDate)
           activate Agenda

           Agenda -> TasksList ** : create()
           loop for each task
               opt assignedTeam exists in teamsDTO
                   Agenda -> Task : betweenDates(startDate, endDate)
                   activate Task

                   Task --> Agenda : true/false
                   deactivate Task

                   opt betweenDates == true
                       Agenda -> TasksList : add(task)
                       activate TasksList
                       deactivate TasksList
                   end opt

               end opt

           end loop

       Agenda -> TaskMapper : toDTO(tasks)
       activate TaskMapper

       TaskMapper -> TasksListDTO ** : create()
       loop for each task in TaskList
       TaskMapper -> TasksList : obj = get(i)
       activate TasksList
       deactivate TasksList

       TaskMapper -> TaskMapper : objDTO = toDTO(obj)
       activate TaskMapper

       TaskMapper -> TaskDTO ** : create(...)
       deactivate TaskMapper

       TaskMapper -> TasksListDTO : add(objDTO)
       activate TasksListDTO
       deactivate TasksListDTO

       end loop

       TaskMapper --> Agenda : tasksDTO
       deactivate TaskMapper

       Agenda --> CTRL : tasksDTO
       deactivate Agenda

end group
autonumber 48
<-- CTRL : tasksDTO

@enduml