@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US028 - Consult the tasks assigned to a collaborator

autonumber

actor "Collaborator" as Employee
participant ":ConsultTasksUI" as UI
participant ":ConsultTasksController" as CTRL
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSION
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "taskRepository\n:TaskRepository" as TaskRepository
participant "taskMapper\n:TaskMapper" as TaskMapper
participant "task\n:Task" as Task
participant "tasksList\n:List<Task>" as TasksList
participant "tasksList\n:List<TaskDTO>" as TasksListDTO
participant "taskDTO\n:TaskDTO" as TaskDTO

activate Employee

    Employee -> UI : asks to consult the tasks assigned to collaborator
    activate UI

    UI -> CTRL** : create

    UI --> Employee : requests first date
    deactivate UI

    Employee -> UI : types first date
    activate UI

    UI --> Employee : requests second date
    deactivate UI

    Employee -> UI : types second date
    activate UI

    UI -> CTRL : getEmailCollaborator()
    activate CTRL

    CTRL -> _APP : getInstance()
    activate _APP

    _APP --> CTRL : appSession
    deactivate _APP

    CTRL -> APP : getCurrentSession()
    activate APP

    APP --> CTRL : currentSession
    deactivate APP

    CTRL -> SESSION : email = getUser(email)
    activate SESSION

    SESSION --> CTRL : email
    deactivate SESSION

    CTRL --> UI : email
    deactivate CTRL

    UI -> CTRL : getTasks(email, startDate, endDate)
    activate CTRL

        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

        RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getTaskRepository()
        activate PLAT

        PLAT --> CTRL: taskRepository
        deactivate PLAT

        CTRL -> TaskRepository : getTasksByCollaborator(email)
        activate TaskRepository

        TaskRepository -> TasksList ** : create()
        loop for each task
        TaskRepository -> Task : hasCollaboratorEmail(email)
        activate Task

        Task --> TaskRepository : true/false
        deactivate Task

        TaskRepository -> Task : betweenDates(startDate, endDate)
        activate Task

        Task --> TaskRepository : true/false
        deactivate Task

        opt hasCollaboratorEmail == true && betweenDates == true
            TaskRepository -> TasksList : add(task)
            activate TasksList
            deactivate TasksList
        end opt

        end loop

        TaskRepository --> CTRL : tasks
        deactivate TaskRepository

        CTRL -> TaskMapper : toDTO(tasks)
        activate TaskMapper

        TaskMapper -> TasksListDTO ** : create()
        loop for each task in TaskList
        TaskMapper -> TasksList : obj = get(i)
        activate TasksList
        deactivate TasksList

        TaskMapper -> TaskMapper : objDTO = toDTO(obj)
        activate TaskMapper

        TaskMapper -> TaskDTO ** : create(...)
        deactivate TaskMapper

        TaskMapper -> TasksListDTO : add(objDTO)
        activate TasksListDTO
        deactivate TasksListDTO

        end loop

        TaskMapper --> CTRL : tasksDTO
        deactivate TaskMapper

    CTRL --> UI : tasksDTO
    deactivate CTRL

    UI --> Employee : asks if collaborator wants to view tasks filtered by status
    deactivate UI

    Employee -> UI : answers yes or no
    activate UI

    opt answer is yes
        UI -> CTRL : getStatusList()
        activate CTRL

        CTRL -> TaskRepository : getStatusList()
        activate TaskRepository

        TaskRepository --> CTRL : statusList
        deactivate TaskRepository

        CTRL --> UI : statusList
        deactivate CTRL

        UI --> Employee : shows status list and requests one to filter tasks
        deactivate UI

        Employee -> UI : selects one status
        activate UI

        UI -> CTRL : consultTasksByStatus(tasksDTO, status)
        activate CTRL

        CTRL --> CTRL : filterTasks(tasksDTO, status)
        CTRL --> CTRL : orderTasksByDate(tasksDTO)

        CTRL --> UI : tasksDTO
        deactivate CTRL
    end opt

    opt answer is no
        UI -> CTRL : consultTasks(tasksDTO)
        activate CTRL

        CTRL --> CTRL : orderTasksByDate(tasksDTO)

        CTRL --> UI : tasksDTO
        deactivate CTRL
    end opt

    UI --> Employee : shows tasks assigned to collaborator \nbetween two dates requested
    deactivate UI

deactivate Employee
@enduml