@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":ConsultTasksController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "taskRepository\n:TaskRepository" as TaskRepository
participant "taskMapper\n:TaskMapper" as TaskMapper
participant "task\n:Task" as Task
participant "tasksList\n:List<Task>" as TasksList
participant "tasksList\n:List<TaskDTO>" as TasksListDTO
participant "taskDTO\n:TaskDTO" as TaskDTO

autonumber 34
-> CTRL : getTasks(teamsDTO, startDate, endDate)

autonumber 34.1

activate CTRL
    group Get Tasks By Date Range
           CTRL -> TaskRepository : getTasks(teamsDTO, startDate, endDate)
           activate TaskRepository

           TaskRepository -> TasksList ** : create()
           loop for each task
               opt assignedTeam exists in teamsDTO
                   TaskRepository -> Task : betweenDates(startDate, endDate)
                   activate Task

                   Task --> TaskRepository : true/false
                   deactivate Task

                   opt betweenDates == true
                       TaskRepository -> TasksList : add(task)
                       activate TasksList
                       deactivate TasksList
                   end opt

               end opt

           end loop

           TaskRepository --> CTRL : tasks
           deactivate TaskRepository

       CTRL -> TaskMapper : toDTO(tasks)
       activate TaskMapper

       TaskMapper -> TasksListDTO ** : create()
       loop for each task in TaskList
       TaskMapper -> TasksList : obj = get(i)
       activate TasksList
       deactivate TasksList

       TaskMapper -> TaskMapper : objDTO = toDTO(obj)
       activate TaskMapper

       TaskMapper -> TaskDTO ** : create(...)
       deactivate TaskMapper

       TaskMapper -> TasksListDTO : add(objDTO)
       activate TasksListDTO
       deactivate TasksListDTO

       end loop

       TaskMapper --> CTRL : tasksDTO
       deactivate TaskMapper

end group
autonumber 48
<-- CTRL : tasksDTO

@enduml