@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US028 - Consult the tasks assigned to a collaborator

autonumber

actor "Collaborator" as Employee
participant ":ConsultTasksUI" as UI
participant ":ConsultTasksController" as CTRL
participant "taskRepository\n:TaskRepository" as TaskRepository

activate Employee

    Employee -> UI : asks to consult the tasks assigned to collaborator
    activate UI

    UI -> CTRL** : create

    UI --> Employee : requests first date
    deactivate UI

    Employee -> UI : types first date
    activate UI

    UI --> Employee : requests second date
    deactivate UI

    Employee -> UI : types second date
    activate UI

    UI -> CTRL : getEmailCollaborator()
    activate CTRL

    ref over CTRL
        Get Collaborator's Email
    end ref

    CTRL --> UI : email
    deactivate CTRL

    UI -> CTRL : getTasks(email, startDate, endDate)
    activate CTRL

    ref over CTRL
        Get Tasks List by Collaborator and Date Range
    end ref

    CTRL --> UI : tasksDTO
    deactivate CTRL

    UI --> Employee : asks if collaborator wants to view tasks filtered by status
    deactivate UI

    Employee -> UI : answers yes or no
    activate UI

    opt answer is yes
        UI --> Employee : shows status list and requests one to filter tasks
        deactivate UI

        Employee -> UI : selects one status
        activate UI

        UI -> CTRL : getStatusList()
        activate CTRL

        CTRL -> TaskRepository : getStatusList()
        activate TaskRepository

        TaskRepository --> CTRL : statusList
        deactivate TaskRepository

        CTRL --> UI : statusList
        deactivate CTRL

        UI -> CTRL : consultTasksByStatus(tasksDTO)
        activate CTRL

        CTRL -> TaskRepository : consultTasksByStatus(tasksDTO, status)
        activate TaskRepository

        TaskRepository --> TaskRepository : getTasksByStatus(tasksDTO, status)
        TaskRepository --> TaskRepository : orderTasksByDate()
        TaskRepository --> CTRL : tasksDTO
        deactivate TaskRepository

        CTRL --> UI : tasksDTO
        deactivate CTRL
    end opt

    opt answer is no
        UI -> CTRL : consultTasks(tasksDTO)
        activate CTRL

        CTRL -> TaskRepository : consultTasks(tasksDTO)
        activate TaskRepository

        TaskRepository --> TaskRepository : orderTasksByDate()
        TaskRepository --> CTRL : tasksDTO
        deactivate TaskRepository
        CTRL --> UI : tasksDTO
        deactivate CTRL
    end opt

    UI --> Employee : shows tasks assigned to collaborator \nbetween two dates requested
    deactivate UI

deactivate Employee
@enduml