@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":ConsultTasksController" as CTRL
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSION

autonumber 9
-> CTRL : getEmailCollaborator()

autonumber 9.1

activate CTRL
    group Get Email of Collaborator
           CTRL -> _APP : getInstance()
           activate _APP

           _APP --> CTRL : appSession
           deactivate _APP

           CTRL -> APP : getCurrentSession()
           activate APP

           APP --> CTRL : currentSession
           deactivate APP

           CTRL -> SESSION : email = getUser(email)
           activate SESSION

           SESSION --> CTRL : email
           deactivate SESSION

end group
autonumber 16
<-- CTRL : email

@enduml