
@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US027- As a GSM, I need to list all green spaces

autonumber

actor "GSM" as GSM
participant ":System" as System

activate GSM

    GSM -> System : asks to produce a list of the Green Spaces
    activate System

    loop until end of Green Space list
    System --> GSM : requests to update the current names of the Green Space
    deactivate System
    GSM -> System : updates the current kms of the vehicle
    activate System
    end

    System --> GSM : produces a list of the Green Spaces
    deactivate System

@enduml
