@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Vehicle {
  - String vehiclePlate
  - String brand
  - String model
  - String type
  - Integer tare
  - Integer grossWeight
  - Integer currentKms
  - Integer checkUpFrequency
  - Date registerDate
  - Date acquisitionDate
  + updateVehicleKms(vehiclePlate, kms)
}

class Maintenance {
    - String vehiclePlate
    - Date date
    - Integer kms
}

class ListVehiclesNeedingMaintenanceUI {
}

class ListVehiclesNeedingMaintenanceController {
    + ListVehiclesNeedingMaintenanceController(vehicleRepository, maintenanceRepository)
    + getVehiclesList()
    + updateVehicleKms(vehiclePlate, kms)
    + getLastMaintenance(vehiclePlate)
    + calculateNextMaintenance(vehicle, lastMaintenance)
    + addVehicleToList(vehicle)

}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getVehicleRepository()
}

class VehicleRepository {
    + getVehiclesList()
    + updateVehicleKms(vehiclePlate, kms)
}

class MaintenanceRepository {
    + getLastMaintenance(vehiclePlate)
}


Repositories -> Repositories : instance
Repositories --> "1" VehicleRepository: vehicleRepository
Repositories ---> "1" MaintenanceRepository: maintenanceRepository
ListVehiclesNeedingMaintenanceController ...> Repositories: repositories
ListVehiclesNeedingMaintenanceController ..> VehicleRepository: vehicleRepository
ListVehiclesNeedingMaintenanceController ...> MaintenanceRepository: maintenanceRepository

ListVehiclesNeedingMaintenanceUI ..> ListVehiclesNeedingMaintenanceController
Vehicle "1" --> "*" Maintenance : needs

VehicleRepository "1" --> "*" Vehicle : vehicles
MaintenanceRepository "1" --> "*" Maintenance : maintenances


@enduml