@startuml
skinparam classAttributeIconSize 0

class RegisterGreenSpaceController {
     + RegisterGreenSpaceController(GreenSpaceRepository)
        + GreenSpace(name, type, area, adress)

}


class RegisterGreenSpaceUI {

}

class GreenSpace
{
    - String name
    - String Type
    - int area
    - int adress
    + GreenSpace(name, type, area, adress)
}
class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getGreenSpaceRepository()
}

class GreenSpaceRepository {
   + getGreenSpacebyName(name)
}

class GreenSpaceMapper {
    + List<GreenSpaceDTO> toDTO(List<GreenSpace> greenSpaces)
    + GreenSpaceDTO toDTO(GreenSpace greenSpace)
}
class GreenSpaceDTO{
    - String name
    - String Type
    - int area
    - int adress
    + GreenSpaceDTO(name, type, area, adress)
}

RegisterGreenSpaceUI ..> RegisterGreenSpaceController
RegisterGreenSpaceController ..> GreenSpaceRepository : greenSpaceRepository
GreenSpaceRepository ---> GreenSpace : greenSpace
Repositories ..> GreenSpaceRepository : greenSpaceRepository
RegisterGreenSpaceController ..> Repositories : repositories
GreenSpaceMapper ..> GreenSpace
GreenSpaceMapper ..> GreenSpaceDTO
GreenSpaceRepository ..> GreenSpaceMapper : greenSpaceMapper

'RegisterGreenSpaceController ..> GreenSpace : greenSpace

@enduml