@startuml

left to right direction

actor "Human Resources Manager" as HRM
actor "Fleet Manager" as FM


rectangle RealEstateUSA {
  HRM --> (US 01 - Register skills that might be appointed to a collaborator)
  HRM --> (US 02 - Register a job)
  HRM --> (US 03 - register a collaborator with a job and fundamental characteristics)
  HRM --> (US 04 - Assign one or more skills to a collaborator)
  HRM --> (US 05 - Generate a team proposal automatically)
  FM --> (US 06 - Register a vehicle's information)
  FM --> (US 07 - Register a vehicle’s check-up)


}

@enduml