@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US28 - Consult the tasks assigned to \n a collaborator between two dates

autonumber

actor "Collaborator" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to consult the tasks assigned to collaborator
    activate System

    System --> Employee : requests first date
    deactivate System

    Employee -> System : types first date
    activate System

    System --> Employee : requests second date
    deactivate System

    Employee -> System : types second date
    activate System

    System --> Employee : asks if collaborator wants to view tasks filtered by status
    deactivate System

    Employee -> System : answers yes or no
    activate System

    opt answer is yes
    System --> Employee : shows status list and requests one to filter tasks
    deactivate System

    Employee -> System : selects one status
    activate System
    end opt

    System --> Employee : shows tasks assigned to collaborator between those two dates
    deactivate System

@enduml