@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class RegisterMaintenanceController {
    +registerMaintenance(vehiclePlate, date, kms)
}


class RegisterMaintenanceUI {
}

class Vehicle {
  - String vehiclePlate
      - String brand
      - String model
      - String type
      - Integer tare
      - Integer grossWeight
      - Integer currentKms
            - Integer checkUpFrequency
      - Date registerDate
      - Date acquisitionDate

}
class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getVehicleRepository()
}


class Maintenance {
    - String vehiclePlate
    - Date date
    - Integer kms
}
class VehicleRepository {
    + createMaintenance()
}

Repositories -> Repositories : instance
RegisterMaintenanceUI ..> RegisterMaintenanceController
Vehicle "1" --> "*" Maintenance : has
RegisterMaintenanceController ...> Repositories: repositories
Repositories --> "1" VehicleRepository: vehicleRepository
RegisterMaintenanceController ..> VehicleRepository: vehicleRepository
VehicleRepository "1" --> "*" Vehicle : vehicles




@enduml