@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class AddEntryAgendaUI
{

}

class AddEntryAgendaController
{
    + AddEntryAgendaController()
    + getToDoListEntries()
    + getSelectedTask(i)
    + addEntry(startingDate)
}

class ApplicationSession
{
    + static getInstance()
    + getCurrentSession()
}

class Repositories
{
    - Repositories()
    + getInstance() : Repositories
    + getToDoList()
    + getAgenda()
}

class UserSession
{
    + getUserEmail()
}

class ToDoList
{
    - List<Task> entriesList
    - List<Task> associatedToDoEntriesList
    + getToDoListEntries(email)
    + getSelectedTask(i)
}

class GreenSpace
{
    - String name
    - String type
    - int area
    - String address
    - String gsmEmail
    + hasUserEmail(email)
}

class GreenSpaceDto
{
    - String name
    - String type
    - int area
    - String address
    + GreenSpaceDto(name, type, area, address)
}

class TaskMapper
{
    - List<TaskDto> associatedToDoEntriesListDto
    + toDTO(associatedToDoEntriesList)
    - toDTO(obj)
}

class TaskDto
{
    - String title
    - String description
    - String degreeOfUrgency
    - int expectedDuration
    - Calendar startingDate
    + TaskDto(title, description, degreeOfUrgency, expectedDuration, selectedGreenSpace, startingDate)
}

class Task
{
    - String title
    - String description
    - int expectedDuration
    - Calendar startingDate
    + isPending()
    + hasUserEmail(email)
    + clone(selectedTask)
    + setStartingDate(startingDate)
}

enum DegreeOfUrgency
{
    Low
    Medium
    High
}

enum GSTaskStatus
{
    Pending
    Processed
    Planned
    Postponed
    Canceled
    Done
}

class Agenda
{
    + addEntry(startingDate, selectedTaskClone)
    - add(selectedTaskClone)
}

Task +-- DegreeOfUrgency
Task +-- GSTaskStatus

Repositories -> Repositories : instance
ApplicationSession -> ApplicationSession : instance

AddEntryAgendaUI .> AddEntryAgendaController

AddEntryAgendaController .> Repositories : repositories

Repositories -> "1" Agenda
Repositories -> "1" ToDoList

AddEntryAgendaController ..> ApplicationSession
AddEntryAgendaController ..> UserSession
AddEntryAgendaController ..> ToDoList : toDoList
AddEntryAgendaController ..> Agenda : agenda
AddEntryAgendaController ..> TaskMapper

ToDoList "1" --> "*" Task
Agenda "1" --> "*" Task

Task "*" --> "1" GreenSpace
TaskDto "*" --> "1" GreenSpaceDto

TaskMapper ..> TaskDto
TaskMapper ..> Task
TaskMapper ..> GreenSpaceDto

ApplicationSession --> "1" UserSession : userSession

@enduml