@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model us002



class HRM {
    name : string
    id : int
}

class Job {
    jobName : string
    jobDescription : string

}
class Collaborator {
    name : string
    numCC : int
    phoneNumber : string
    email : string
    birthDate : date
    admissionDate : date
    adress : string
    number : int
    }

class Team {
     name: string
     id: int
     TeamDescription: string
}
Collaborator "*" -- "1" Team : form >
HRM "1" -- "1..." Job : creates >
Collaborator "*" - "1..*" Job : do >

@enduml