@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US024 - Postpone an entry in the agenda

autonumber

actor "GSM" as Employee
participant ":PostponeEntryUI" as UI
participant ":PostponeEntryController" as CTRL
participant "taskRepository\n:TaskRepository" as TaskRepository
participant "taskDTO\n:TaskDTO" as TaskDTO


activate Employee

    Employee -> UI : asks to postpone an entry in the agenda
    activate UI

    UI --> CTRL** : create()
    UI -> CTRL : getGreenSpaces()
    activate CTRL

    ref over CTRL
        Get Green Spaces
    end ref

    CTRL --> UI : GSMGreenSpacesListDto
    deactivate CTRL

    UI --> Employee : shows list of green spaces to select one
    deactivate UI

    Employee -> UI : selects one green space
    activate UI

    UI -> CTRL : getEntriesByGreenSpace()
    activate CTRL

    ref over CTRL
        Get Tasks by Green Space
    end ref

    CTRL --> UI : entriesListByGreenSpaceDTO
    deactivate CTRL

    UI --> Employee : shows list of entries in the agenda of the selected green space
    deactivate UI

    Employee -> UI : selects one entry
    activate UI

    UI --> Employee : requests the new date
    deactivate UI

    Employee -> UI : types the new date
    activate UI

    UI -> CTRL : postponeEntry(taskDTO, newDate)
    activate CTRL

    CTRL --> CTRL : validateNewDate(newDate)
    CTRL -> TaskRepository : postponeEntry(taskDTO, newDate)
    activate TaskRepository

    TaskRepository -> TaskDTO : postponeEntry(taskDTO, newDate)
    activate TaskDTO

    TaskDTO --> TaskRepository : taskDTO
    deactivate TaskDTO

    TaskRepository --> CTRL : taskDTO
    deactivate TaskRepository

    CTRL --> UI : taskDTO
    deactivate CTRL

    UI --> Employee : displays operation success
    deactivate UI

deactivate Employee

@enduml