@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":PostponeEntryController" as CTRL
participant "repositories\n:Repositories" as PLAT
participant "taskMapper\n:TaskMapper" as TaskMapper
participant "agenda\n:Agenda" as Agenda
participant "entriesList\n:List<Task>" as entriesList
participant "entriesListByGreenSpace\n:List<Task>" as entriesListByGreenSpace
participant "task\n:Task" as task
participant "entriesListByGreenSpaceDTO\n:List<TaskDTO>" as entriesListByGreenSpaceDTO
participant "taskDTO\n:TaskDTO" as TaskDTO

autonumber 30
-> CTRL : getTasksByGreenSpace(greenSpaceDTO)

autonumber 30.1

activate CTRL
    group Get Tasks By Green Space
           CTRL -> PLAT : getAgenda()
           activate PLAT

           PLAT --> CTRL : agenda
           deactivate PLAT

           CTRL -> Agenda : getAgendaEntries(greenSpace)
           activate Agenda

           Agenda --> entriesListByGreenSpace** : create()

           loop for each known task

           Agenda -> entriesList : entry = get(i)
           activate entriesList
           deactivate entriesList

           Agenda -> task : taskGreenSpace = greenSpace
           activate task
           deactivate task

           opt greenSpace == true
           Agenda -> entriesListByGreenSpace : add(entry)
           activate entriesListByGreenSpace
           deactivate entriesListByGreenSpace
           end opt

           end loop

           Agenda --> CTRL : entriesListByGreenSpace
           deactivate Agenda

           CTRL -> TaskMapper : toDTO(entriesList)
           activate TaskMapper

           TaskMapper --> entriesListByGreenSpaceDTO** : create()

           loop for each task in entriesListByGreenSpace

           TaskMapper -> entriesListByGreenSpace : obj = get(i)
           activate entriesListByGreenSpace
           deactivate entriesListByGreenSpace

           TaskMapper -> TaskMapper : objDto = toDTO(obj)
           activate TaskMapper

           TaskMapper -> TaskDTO** : create(...)
           deactivate TaskMapper

           TaskMapper -> entriesListByGreenSpaceDTO : add(objDto)
           activate entriesListByGreenSpaceDTO
           deactivate entriesListByGreenSpaceDTO

           end loop

           TaskMapper --> CTRL : entriesListByGreenSpaceDTO
           deactivate TaskMapper

end group
autonumber 46
<-- CTRL : entriesListByGreenSpaceDTO

@enduml