@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US024 - Postpone an entry in the agenda

autonumber

actor "GSM" as Employee
participant ":PostponeEntryUI" as UI
participant ":PostponeEntryController" as CTRL
participant "taskRepository\n:TaskRepository" as TaskRepository
participant "taskDto\n:TaskDto" as TaskDto

activate Employee

    Employee -> UI : asks to postpone an entry in the agenda
    activate UI

    UI -> CTRL** : create

                UI -> CTRL : getGreenSpaces()
                activate CTRL

                    ref over CTRL
                        Get Green Spaces
                    end

                    CTRL --> UI : greenSpacesDTO
                deactivate CTRL

    UI --> Employee : shows list of green spaces to select one
    deactivate UI

    Employee -> UI : selects the green space
    activate UI

        UI -> CTRL : getTasksByGreenSpace(greenSpaceDTO)
        activate CTRL

            ref over CTRL
               Get Tasks by Green Space
            end

            CTRL --> UI : tasksByGreenSpaceDTO
        deactivate CTRL

    UI --> Employee : shows list of entries in the agenda of the selected green space
    deactivate UI

    Employee -> UI : selects one entry
    activate UI

    UI --> Employee : requests the new date
    deactivate UI

    Employee -> UI : types the new date
    activate UI

    UI -> CTRL : postponeEntry(taskDTO, newDate)
    activate CTRL

    CTRL --> CTRL : validateNewDate(newDate)
    CTRL -> TaskRepository : postponeEntry(taskDTO, newDate)
    activate TaskRepository

    TaskRepository -> TaskDto : startingDate = newDate
    activate TaskDto
    deactivate TaskDto

    deactivate TaskRepository
    deactivate CTRL


    UI --> Employee : displays operation success
    deactivate UI

deactivate Employee
@enduml