@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US024 - Postpone an entry in the agenda

autonumber

actor "GSM" as Employee
participant ":PostponeEntryUI" as UI
participant ":PostponeEntryController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "greenSpaceRepository\n:GreenSpaceRepository" as GreenSpaceRepository
participant "taskRepository\n:TaskRepository" as TaskRepository

activate Employee

    Employee -> UI : asks to postpone an entry in the agenda
    activate UI

    UI -> CTRL** : create

                UI -> CTRL : getGreenSpaces()
                activate CTRL

                    CTRL -> RepositorySingleton : getInstance()
                    activate RepositorySingleton

                        RepositorySingleton --> CTRL: repositories
                    deactivate RepositorySingleton

                    CTRL -> PLAT : getGreenSpaceRepository()
                    activate PLAT

                        PLAT --> CTRL: greenSpaceRepository
                    deactivate PLAT

                    CTRL -> GreenSpaceRepository : getGreenSpaces()
                    activate GreenSpaceRepository

                        GreenSpaceRepository --> CTRL : greenSpaces
                    deactivate GreenSpaceRepository

                    CTRL --> UI : greenSpaces
                deactivate CTRL

    UI --> Employee : shows list of green spaces to select one
    deactivate UI

    Employee -> UI : selects the green space
    activate UI

        UI -> CTRL : getTasksByGreenSpace(greenSpace)
        activate CTRL

            CTRL -> RepositorySingleton : getInstance()
            activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getTaskRepository()
            activate PLAT

            PLAT --> CTRL: taskRepository
            deactivate PLAT

            CTRL -> TaskRepository : getTasksByGreenSpace(greenSpace)
            activate TaskRepository

            TaskRepository --> CTRL : tasksByGreenSpace
            deactivate TaskRepository

            CTRL --> UI : tasksByGreenSpace
        deactivate CTRL

    UI --> Employee : shows list of entries in the agenda of the selected green space
    deactivate UI

    Employee -> UI : selects one entry
    activate UI

    UI --> Employee : requests the new date
    deactivate UI

    Employee -> UI : types the new date
    activate UI

    UI -> CTRL : postponeEntry(task, newDate)
    activate CTRL

    CTRL -> TaskRepository : postponeEntry(task, newDate)
    activate TaskRepository

    TaskRepository -> TaskRepository : validateNewDate(newDate)

    TaskRepository --> CTRL : entry
    deactivate TaskRepository

    CTRL --> UI : entry
    deactivate CTRL

    UI --> Employee : displays operation success
    deactivate UI

deactivate Employee
@enduml