@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":PostponeEntryController" as CTRL
participant ":ApplicationSession" as _APP
participant "appSession\n:ApplicationSession" as APP
participant "currentSession\n:UserSession" as SESSION
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "greenSpaceRepository\n:GreenSpaceRepository" as GreenSpaceRepository
participant "greenSpacesList\n:List<GreenSpace>" as greenSpacesList
participant "greenSpaceMapper\n:GreenSpaceMapper" as GreenSpaceMapper
participant "greenSpace\n:GreenSpace" as greenSpace
participant "GSMGreenSpacesList\n:List<GreenSpace>" as GSMGreenSpacesList
participant "GSMGreenSpacesListDto\n:List<GreenSpaceDto>" as GSMGreenSpacesListDto
participant "greenSpaceDTO\n:GreenSpaceDTO" as greenSpaceDTO

autonumber 3
-> CTRL : getGreenSpaces()

autonumber 3.1

activate CTRL
    group Get Green Spaces

           CTRL -> _APP: getInstance()
           activate _APP

           _APP -> CTRL: appSession
           deactivate _APP

           CTRL -> APP: getCurrentSession()
           activate APP

           APP --> CTRL: currentSession
           deactivate APP

           CTRL -> SESSION: email = getUserEmail()
           activate SESSION

           SESSION --> CTRL: email
           deactivate SESSION

           CTRL -> RepositorySingleton : getInstance()
           activate RepositorySingleton

           RepositorySingleton --> CTRL: repositories
           deactivate RepositorySingleton

           CTRL -> PLAT : getGreenSpaceRepository()
           activate PLAT

           PLAT --> CTRL : greenSpaceRepository
           deactivate PLAT

           CTRL -> GreenSpaceRepository : getGreenSpaces(email)
           activate GreenSpaceRepository

           GreenSpaceRepository --> GSMGreenSpacesList** : create()

           loop for each known Green Space
           GreenSpaceRepository -> greenSpacesList : greenSpace = get(i)
           activate greenSpacesList
           deactivate greenSpacesList

           GreenSpaceRepository -> greenSpace : GSM = hasUserEmail(email)
           activate greenSpace
           deactivate greenSpace

           opt hasUserEmail
           GreenSpaceRepository -> GSMGreenSpacesList : add(greenSpace)
           activate GSMGreenSpacesList
           deactivate GSMGreenSpacesList
           end opt

           end loop

           GreenSpaceRepository -> GreenSpaceMapper : toDTO(GSMGreenSpacesList)
           activate GreenSpaceMapper

           GreenSpaceMapper --> GSMGreenSpacesListDto** : create()

           loop for each object in GSMGreenSpacesList
           GreenSpaceMapper -> GSMGreenSpacesList : obj = get(i)
           activate GSMGreenSpacesList

           deactivate GSMGreenSpacesList

           GreenSpaceMapper -> GreenSpaceMapper : objDto = toDTO(obj)
           activate GreenSpaceMapper

           GreenSpaceMapper -> greenSpaceDTO** :create(...)
           deactivate GreenSpaceMapper

           GreenSpaceMapper -> GSMGreenSpacesListDto : add(objDto)
           activate GSMGreenSpacesListDto

           deactivate GSMGreenSpacesListDto

           end loop

           GreenSpaceMapper --> GreenSpaceRepository : GSMGreenSpacesListDto
           deactivate GreenSpaceMapper

           GreenSpaceRepository --> CTRL : GSMGreenSpacesListDto
           deactivate GreenSpaceRepository


end group
autonumber 27
<-- CTRL : GSMGreenSpacesListDto

@enduml