@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class FM {
}


class Checkup {
    date
    kms
}

FM "1" -- "*" Checkup : registers >

@enduml