@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

       title US029 - Record the completion of a task.

autonumber

actor "Collaborator" as Employee
participant ":CompleteTaskUI" as UI
participant ":CompleteTaskController" as CTRL
participant "taskRepository\n:TaskRepository" as TaskRepository

activate Employee

    Employee -> UI : asks to change task status to complete
    activate UI

  UI --> CTRL** : create()
    UI -> CTRL : getTasks()
                activate CTRL
 ref over CTRL
        Get Tasks by email
    end ref

                        CTRL --> UI : CollaboratorTasksListDto
                        deactivate CTRL
       UI --> Employee : shows list of own tasks
       deactivate UI

    Employee -> UI : selects a task
    activate UI

    UI --> Employee : requests confirmation of completion of task
    deactivate UI

   Employee -> UI : confirms
       activate UI
    UI -> CTRL : completeTask(taskDTO, newStatus)
       activate CTRL

       CTRL --> CTRL : validateNewStatus(newStatus)
       CTRL -> TaskRepository :  completeTask(taskDTO, newStatus)
       activate TaskRepository

       TaskRepository -> TaskDTO :  completeTask(taskDTO, newStatus)
       activate TaskDTO

       TaskDTO --> TaskRepository : taskDTO
       deactivate TaskDTO

       TaskRepository --> CTRL : taskDTO
       deactivate TaskRepository

       CTRL --> UI : taskDTO
       deactivate CTRL

       UI --> Employee : displays operation success
       deactivate UI

   deactivate Employee
@enduml