@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

       title US029 - Record the completion of a task.

autonumber

actor "Collaborator" as Employee
participant ":ChangeStatusUI" as UI
participant ":ChangeStatusController" as CTRL
participant "taskRepository\n:TaskRepository" as TaskRepository

activate Employee

    Employee -> UI : asks to change task status to complete
    activate UI

    UI -> CTRL** : create









    UI -> CTRL : getEmailCollaborator()
    activate CTRL

    ref over CTRL
        Get Email
    end

    CTRL --> UI : email
    deactivate CTRL

    UI -> CTRL : getTasksByCollaborator(email)
    activate CTRL

    ref over CTRL
         Get Tasks by Collaborator
    end

    CTRL --> UI : tasksByCollaborator
    deactivate CTRL


    UI --> Employee : shows list of own tasks
    deactivate UI

    Employee -> UI : selects a task
    activate UI

    UI --> Employee : requests confirmation of completion of task
    deactivate UI

    Employee -> UI : confirms
    activate UI

    UI -> CTRL :            completeTask(taskDTO, newStatusnewStatus)

    activate CTRL

    CTRL --> CTRL : validateNewStatus(newStatus)
    CTRL -> TaskRepository :            completeTask(taskDTO, newStatus)

    activate TaskRepository

    TaskRepository -> TaskDto : status = newStatus
    activate TaskDto
    deactivate TaskDto

    deactivate TaskRepository
    deactivate CTRL


    UI --> Employee : displays operation success
    deactivate UI

deactivate Employee
@enduml