@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model us006

class FM {
    name : string
    id : int
}

class Job {
    jobName : string
    jobDescription : string
}



class Vehicle {
    brand : string
    model : string
    type : string
    Tare : int
    GrossWeight : int
    CurrentKm : int
    RegisterDate : date
    AcquisitionDate : date
    MaintenanceCheckupFrequency : int
}





FM "1.." -- "1" Job : is a >
FM "1" -- "1.." Vehicle : Register >



@enduml

As an FM, I wish to register a vehicle including Brand,
 Model, Type, Tare, Gross Weight, Current Km, Register Date,
  Acquisition Date, Maintenance/Checkup Frequency (in Kms)