@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Skill
{
    - name
    + Skill(name)
}

class Collaborator {
    - name
    - birthdate
    - admissionDate
    - address
    - phoneNumber
    - email
    - taxpayerNumber
    - identificationDocumentType
    - identificationDocumentNumber
    + Collaborator(name, birthdate, admissionDate, address, phoneNumber, email, \ntaxpayerNumber, identificationDocumentType, identificationDocumentNumber)
}

class AssignSkillsController {
    + AssignSkillsController(skillRepository)
    + getSkillsList()
}

class AssignSkillsUI {
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getSkillRepository()
}

class SkillRepository {
    + getSkillsList()
}


Collaborator "1" --> "*" Skill: has
AssignSkillsUI ..> AssignSkillsController
AssignSkillsController ...> Repositories: repositories
AssignSkillsController ..> SkillRepository: skillRepository

Repositories -> Repositories : instance
Repositories --> "1" SkillRepository: skillRepository

SkillRepository --> Skill: skills


@enduml