@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "GSM" as GSM
participant ":RegisterGreenSpaceUI" as UI
participant ":RegisterGreenSpaceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "GreenSpaceRepository:\nGreenSpaceRepository" as GreenSpaceRepository
participant "GreenSpace\n:GreenSpace" as GreenSpace
participant "GreenSpaceMapper\n:GreenSpaceMapper" as GreenSpaceMapper
participant "GreenSpaceList\n:List<GreenSpace>" as GreenSpaceList
participant "greenSpaceDto\n:GreenSpaceDto" as GreenSpaceDto


activate GSM


    GSM -> UI : asks to produce a list of the GreenSpaces
    activate UI

    UI -> CTRL** : create

    UI -> CTRL : createList()
    activate CTRL
    CTRL -> GreenSpaceRepository : createList()
    activate GreenSpaceRepository
    deactivate GreenSpaceRepository
    deactivate CTRL

    UI -> CTRL : getGreenSpacesList()
    activate CTRL
    CTRL -> RepositorySingleton : getInstance()
    activate RepositorySingleton
    RepositorySingleton --> CTRL : repositories
    deactivate RepositorySingleton

    CTRL -> PLAT : getGreenSpaceRepository()
    activate PLAT
    PLAT --> CTRL : GreenSpaceRepository
    deactivate PLAT

    CTRL -> GreenSpaceRepository : getGreenSpaceList()
    activate GreenSpaceRepository
        GreenSpaceRepository -> GreenSpaceList : getGreenSpace()

        activate GreenSpaceList

        GreenSpaceList -> GreenSpaceRepository : GreenSpaceList

        deactivate GreenSpaceList

        GreenSpaceRepository -> GreenSpaceMapper : dtoGreenSpaces(GreenSpace)

        activate GreenSpaceMapper

        GreenSpaceMapper -> GreenSpaceList : greenSpace=get()

        activate GreenSpaceList

        deactivate GreenSpaceList

        GreenSpaceMapper -> GreenSpaceMapper : greenSpaceDto(greenSpace) = dto(greenSpace)

        GreenSpaceMapper -> greenSpaceDto** :create greenSpaceDto()

       GreenSpaceMapper-> GreenSpaceList : add(greenSpaceDto)

       activate GreenSpaceList

       deactivate GreenSpaceList

       GreenSpaceMapper -> GreenSpaceRepository : greenSpaceListdto


    GreenSpaceRepository --> CTRL : GreenSpaceListdto

    deactivate GreenSpaceRepository
    deactivate GreenSpaceMapper
    CTRL --> UI : GreenSpaceListdto
    deactivate CTRL


    UI --> GSM : shows list of GreenSpaces
    deactivate UI
    GSM -> UI : chose one of the sorting options
    activate UI
    UI -> CTRL : sortGreenSpacesList(option)
        activate CTRL
        CTRL -> GreenSpaceRepository : sortGreenSpacesList(option)
        activate GreenSpaceRepository
        GreenSpaceRepository --> CTRL : sortedGreenSpaceList
        deactivate GreenSpaceRepository
        CTRL --> UI : sortedGreenSpaceList
        deactivate CTRL

        UI --> GSM : shows sorted list of GreenSpaces
        deactivate UI

@enduml