@startuml

'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor yellow
}

title Use Case Diagram us006 - As an FM, I wish to register a vehicle
left to right direction

rectangle "System Actor" as actor {
    actor "FM" as FleetManager
}


rectangle "Use Cases" as usecases{
    usecase "UC6_1 - Request to register a new vehicle" as UC6_1
    FleetManager --> UC6_1

}
rectangle "Use Cases" as usecases{
    usecase "UC6_2 - Registers vehicle specifications" as UC6_2
    FleetManager --> UC6_2

}
@enduml