@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US024 - Postpone an entry in the agenda

autonumber

actor "GSM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to postpone an entry in the agenda
    activate System

    System --> Employee : shows list of green spaces to select one
    deactivate System

    Employee -> System : selects the green space
    activate System

    System --> Employee : shows list of entries in the agenda of the selected green space
    deactivate System

    Employee -> System : selects one entry
    activate System

    System --> Employee : requests the new date
    deactivate System

    Employee -> System : types the new date
    activate System

    System --> Employee : postpones entry and displays operation success
    deactivate System

deactivate Employee
@enduml