@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US 026

autonumber

actor "GSM" as GSM
participant ":System" as System

activate GSM

    GSM -> System: selects "Assign  vehicles to the Agenda" option
    activate System

         System --> GSM: request vehicle plate
            deactivate System
                GSM -> System: enters vehicle plate
                    activate System
                       System --> GSM: asks for date

                                deactivate System

                                                GSM -> System: enters date
                                                       activate System
                                    System -> GSM: asks to validate data

                                    deactivate System
                                                                           GSM --> System: confirms data
                                                                                    activate System
                                                                                      System -> GSM: shows operation success
                                                                                      deactivate System
@enduml