@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title US028 - Consult the tasks assigned to a collaborator

class Collaborator {
}

class Agenda {
}

class Task {
    title
    description
    degreeOfUrgency
    expectedDuration
    status
    startingDate
}

class GreenSpace {
    name
    area
    type
    address
}


Task "*" -- "1" Agenda : was added >
Task "1" -- "1" GreenSpace : is associated with >
Collaborator "1" -- "*" Task : is assigned to <

@enduml