@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US008

autonumber

actor "VFM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to list the vehicles needing the check-up
    activate System

    System --> Employee : lists the vehicles needing the check-up
    deactivate System

@enduml