@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US008 - Produce a list of vehicles needing maintenance

autonumber

actor "VFM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to produce a list of the vehicles needing maintenance
    activate System

    System --> Employee : produces a list of the vehicles needing maintenance \n(shows plate, brand, model, current kms, checkup data)
    deactivate System

@enduml