@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class HRM {
}

class Team {
}

class Collaborator {
    name
    birthdate
    admissionDate
    address
    phoneNumber
    email
    taxpayerNumber
    identificationDocumentType
    identificationDocumentNumber
}




HRM "1" - "*" Team : generates >
Team "1" - "1..*" Collaborator : has >

@enduml