@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CancelEntryController" as CTRL
participant "repositories\n:Repositories" as PLAT
participant "taskMapper\n:TaskMapper" as TaskMapper
participant "agenda\n:Agenda" as Agenda
participant "entriesList\n:List<Task>" as entriesList
participant "tasksListByGreenSpace\n:List<Task>" as tasksListByGreenSpace
participant "task\n:Task" as task
participant "tasksListByGreenSpaceDTO\n:List<TaskDTO>" as tasksListByGreenSpaceDTO
participant "taskDTO\n:TaskDTO" as TaskDTO

autonumber 30
-> CTRL : getTasksByGreenSpace(greenSpace)

autonumber 30.1

activate CTRL
    group Get Tasks By Green Space
           CTRL -> PLAT : getAgenda()
           activate PLAT

           PLAT --> CTRL : agenda
           deactivate PLAT

           CTRL -> Agenda : getAgendaTasks(greenSpace)
           activate Agenda

           Agenda --> tasksListByGreenSpace** : create()

           loop for each known task

           Agenda -> entriesList : task = get(i)
           activate entriesList
           deactivate entriesList

           Agenda -> task : taskGreenSpace = greenSpace
           activate task
           deactivate task

           opt greenSpace == true
           Agenda -> tasksListByGreenSpace : add(entry)
           activate tasksListByGreenSpace
           deactivate tasksListByGreenSpace
           end opt

           end loop

           Agenda --> CTRL : tasksListByGreenSpace
           deactivate Agenda

           CTRL -> TaskMapper : toDTO(entriesList)
           activate TaskMapper

           TaskMapper --> tasksListByGreenSpaceDTO** : create()

           loop for each task in tasksListByGreenSpace

           TaskMapper -> tasksListByGreenSpace : obj = get(i)
           activate tasksListByGreenSpace
           deactivate tasksListByGreenSpace

           TaskMapper -> TaskMapper : objDto = toDTO(obj)
           activate TaskMapper

           TaskMapper -> TaskDTO** : create(...)
           deactivate TaskMapper

           TaskMapper -> tasksListByGreenSpaceDTO : add(objDto)
           activate tasksListByGreenSpaceDTO
           deactivate tasksListByGreenSpaceDTO

           end loop

           TaskMapper --> CTRL : tasksListByGreenSpaceDTO
           deactivate TaskMapper

end group
autonumber 46
<-- CTRL : tasksListByGreenSpaceDTO

@enduml