@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":PostponeEntryController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "TaskRepository" as TaskRepository

autonumber 13
-> CTRL : getTasksByGreenSpace(greenSpace)

autonumber 13.1

activate CTRL
    group Get Tasks By Green Space
           CTRL -> RepositorySingleton : getInstance()
           activate RepositorySingleton

           RepositorySingleton --> CTRL: repositories
           deactivate RepositorySingleton

           CTRL -> PLAT : getTaskRepository()
           activate PLAT

           PLAT --> CTRL: taskRepository
           deactivate PLAT

           CTRL -> TaskRepository : getTasksByGreenSpace(greenSpace)
           activate TaskRepository

           TaskRepository --> TaskRepository : getTasksUndone()

           TaskRepository --> CTRL : tasksByGreenSpace
           deactivate TaskRepository

end group
autonumber 14
<-- CTRL : tasksByGreenSpaces

@enduml