@startuml
title Register a new vehicle

skinparam classAttributeIconSize 0


class RegisterNewVehicleController {

    + RegisterNewVehicleController();
    +getVehicle();
    -getVehicleByPlate();

     }

class RegisterNewVehicleUI {

}

class Repositories{
    + getVehicleRepository();
    +Repositories();
    -getinstance();

}
class VehicleRepository{
    +RegisterVehicles();
    +getVehicleByPlate();

}

class Vehicle {
    +Strin brand
    +String vehiclePlate
    +String model
    +String type
    +int Tare
    +int GrossWeight
    +int CurrentKm
    +Date RegisterDate
    +Date AcquisitionDate
    +Date MaintenanceCheckupFrequency
}

RegisterNewVehicleUI ..> RegisterNewVehicleController
RegisterNewVehicleController ..> Repositories : Repositories
Vehicle ..> RegisterNewVehicleController
Repositories ..> VehicleRepository : RegisterVehicleRepository
VehicleRepository ..> Vehicle : Vehicle
@enduml