@startuml



participant ":RegisterNewVehicleController" as RegisterNewVehicleController
participant "Repositories" as Repositories
participant "repositories\n:Repositories" as repRep
participant "RegisterNewVehicleRepository" as RegisterNewVehicleRepository
participant "Vehicle" as Vehicle


-> RegisterNewVehicleController : RegisterVehicle()
group store vehicle
activate RegisterNewVehicleController
RegisterNewVehicleController -> Repositories : getinstance()
activate Repositories
Repositories -> RegisterNewVehicleController : Repositories
deactivate Repositories
RegisterNewVehicleController -> repRep : getVehicleRepository()
activate repRep
repRep -> RegisterNewVehicleController : VehicleRepository
deactivate repRep
RegisterNewVehicleController -> RegisterNewVehicleRepository : RegisterNewVehicle(brand,vehiclePlate, model, type, \nTare, GrossWeight, CurrentKm, RegisterDate, \nAcquisitionDate, MaintenanceCheckupFrequency)
activate RegisterNewVehicleRepository
RegisterNewVehicleRepository -> Vehicle** : RegisterNewVehicle(brand,vehiclePlate, model, type, \nTare, GrossWeight, CurrentKm, RegisterDate, \nAcquisitionDate, MaintenanceCheckupFrequency)
RegisterNewVehicleRepository -> RegisterNewVehicleRepository : Save vehicle
RegisterNewVehicleRepository -> RegisterNewVehicleController : Vehicle
deactivate RegisterNewVehicleRepository
end
<- RegisterNewVehicleController  : Vehicle
deactivate RegisterNewVehicleController
@enduml