@startuml
title Register a new vehicle

skinparam classAttributeIconSize 0

class ApplicationSession
{
  +static getInstance()
  +getCurrentSession()
}

class UserSession
{
  +isLoggedInWithRole(USER_ROLE)
}

class "RegisterNewVehicleController" {
    + RegisterNewVehicleController()
    + methodX(...)
}

class "RegisterNewVehicleUI" {
}

"RegisterNewVehicleUI" ..> "RegisterNewVehicleController" : «uses»
"RegisterNewVehicleController" ..> ApplicationSession
"RegisterNewVehicleController" ..> UserSession

@enduml