@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "VFM" as USER

participant ":RegisterNewVehicleUI" as RegisterNewVehicleUI
participant ":RegisterNewVehicleController" as RegisterNewVehicleController
participant ":RegisterNewVehicleRepository" as RegisterNewVehicleRepository

activate USER
USER -> RegisterNewVehicleUI : asks to register a new vehicle
activate RegisterNewVehicleUI
RegisterNewVehicleUI ->USER : request vehicle data
deactivate RegisterNewVehicleUI

USER -> RegisterNewVehicleUI : types requested vehicle data
activate RegisterNewVehicleUI
RegisterNewVehicleUI -> RegisterNewVehicleController : Registers new vehicle
activate RegisterNewVehicleController
RegisterNewVehicleController -> RegisterNewVehicleRepository :Vehicle inserted in the repository
activate RegisterNewVehicleRepository
RegisterNewVehicleRepository -> RegisterNewVehicleController : vehicle
deactivate RegisterNewVehicleRepository
RegisterNewVehicleController -> RegisterNewVehicleUI : vehicle

deactivate RegisterNewVehicleController

RegisterNewVehicleUI -> USER : Display operation Success
deactivate RegisterNewVehicleUI
deactivate USER


@enduml