@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "VFM" as USER

participant ":RegisterNewVehicleUI" as RegisterNewVehicleUI
participant ":RegisterNewVehicleController" as RegisterNewVehicleController


activate USER
USER -> RegisterNewVehicleUI : asks to register a new vehicle
activate RegisterNewVehicleUI
RegisterNewVehicleUI ->USER : request vehicle data
deactivate RegisterNewVehicleUI

USER -> RegisterNewVehicleUI : types requested vehicle data
activate RegisterNewVehicleUI
RegisterNewVehicleUI -> RegisterNewVehicleController : Registers new vehicle
activate RegisterNewVehicleController
RegisterNewVehicleController -> RegisterNewVehicleUI : Vehicle
deactivate RegisterNewVehicleController

RegisterNewVehicleUI -> USER : Display operation Success
deactivate RegisterNewVehicleUI
deactivate USER























@enduml
activate USER

    USER -> MENU : selects an option
    activate MENU
        MENU --> RegisterNewVehicleUI** : create
        activate RegisterNewVehicleUI

            RegisterNewVehicleUI --> RegisterNewVehicleController** : create
        deactivate RegisterNewVehicleUI

        activate RegisterNewVehicleController
            RegisterNewVehicleController -> APPSESSIONC : getinstance()
            note right
                static method
                (Singleton pattern)
            end note
            activate APPSESSIONC
                APPSESSIONC --> RegisterNewVehicleController : appSession
            deactivate APPSESSIONC

            RegisterNewVehicleController -> APPSESSIONI : getCurrentSession()
            activate APPSESSIONI
                APPSESSIONI --> RegisterNewVehicleController : currentSession
            deactivate APPSESSIONI
        deactivate RegisterNewVehicleController

        MENU -> RegisterNewVehicleUI : run()
        activate RegisterNewVehicleUI
    deactivate MENU

            RegisterNewVehicleUI --> USER : requests something
            |||
        deactivate RegisterNewVehicleUI

    loop
        USER -> RegisterNewVehicleUI : does something
        activate RegisterNewVehicleUI
            RegisterNewVehicleUI -> RegisterNewVehicleController : methodX(...)
            activate RegisterNewVehicleController
                RegisterNewVehicleController -> APPSESSIONC : methodY(...)
                activate APPSESSIONC
                    ref over APPSESSIONC,APPSESSIONI,CURSESSION


                    end ref
                    APPSESSIONC --> RegisterNewVehicleController : answer
                deactivate APPSESSIONC

                RegisterNewVehicleController --> RegisterNewVehicleUI : answer
            deactivate RegisterNewVehicleController

            RegisterNewVehicleUI --> USER : answers/requests another thing
            |||
        deactivate RegisterNewVehicleUI
    end loop

deactivate USER

@enduml