@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

participant ":RegisterNewVehicleController" as RegisterNewVehicleController
participant "Repositories" as Repositories
participant ":RegisterNewVehicleRepository" as RegisterNewVehicleRepository

-> RegisterNewVehicleController: registerNewVehicle()
group RegisterVehicle
activate RegisterNewVehicleController
RegisterNewVehicleController -> Repositories : getRepository()
activate Repositories
Repositories -> RegisterNewVehicleController : VehicleRepositor
deactivate Repositories
RegisterNewVehicleController -> RegisterNewVehicleRepository : RegisterNewVehicleRepository()
activate RegisterNewVehicleRepository
RegisterNewVehicleRepository -> RegisterNewVehicleController : Vehicles
deactivate RegisterNewVehicleRepository
end
<- RegisterNewVehicleController : Vehicle

@enduml