@startuml
title Register a new vehicle

skinparam classAttributeIconSize 0


class RegisterNewVehicleController {
    + registerVehicle(brand : String,
                           vehiclePlate : String,
                           model : String,
                           type : String,
                           Tare : int,
                           GrossWeight : int,
                           CurrentKm : int,
                           RegisterDate : Date,
                           AcquisitionDate : Date,
                           MaintenanceCheckupFrequency : int,)

                           + RegisterNewVehicleController()
     }

class RegisterNewVehicleUI {
    +main(args: String[]): void
}

class Repositories{
    + RegisterNewVehicleRepository()
}
class RegisterNewVehicleView {
    displayForm() {
    }

class Vehicle {
    brand
    vehiclePlate
    model
    type
    Tare
    GrossWeight
    CurrentKm
    RegisterDate
    AcquisitionDate
    MaintenanceCheckupFrequency
}

RegisterNewVehicleUI ..> RegisterNewVehicleController : inputs wanted data
RegisterNewVehicleController ..> Repositories : «saves in»
Vehicle ..> RegisterNewVehicleController : «depends on»
RegisterNewVehicleController ..> RegisterNewVehicleView : «uses»
RegisterNewVehicleView..> RegisterNewVehicleUI : dysplays
@enduml