@startuml
title Register a new vehicle

skinparam classAttributeIconSize 0


class RegisterNewVehicleController {
    + RegisterNewVehicleController()

    + registerVehicle(brand : String,
                           vehiclePlate : String,
                           model : String,
                           type : String,
                           Tare : int,
                           GrossWeight : int,
                           CurrentKm : int,
                           RegisterDate : Date,
                           AcquisitionDate : Date,
                           MaintenanceCheckupFrequency : int,)
     }

class RegisterNewVehicleUI {
    +main(args: String[]): void
}

class RegisterNewVehicleRepository{
    + saveVehicle()
}

class Vehicle {
    brand
    vehiclePlate
    model
    type
    Tare
    GrossWeight
    CurrentKm
    RegisterDate
    AcquisitionDate
    MaintenanceCheckupFrequency
}

RegisterNewVehicleUI ..> RegisterNewVehicleController : «uses»
RegisterNewVehicleController ..> RegisterNewVehicleRepository : «saves in»
Vehicle ..> RegisterNewVehicleController : «depends on»
@enduml