@startuml

left to right direction

actor "Human Resources Manager" as HRM
actor "Vehicle and Equipment Fleet Manager" as VFM


rectangle GreenSpaceManagement {
  HRM --> (UC 001 - Register skills)
  HRM --> (UC 002 - Register a job)
  HRM --> (UC 003 - Register a collaborator)
  HRM --> (UC 004 - Assign skills to a collaborator)
  HRM --> (UC 005 - Generate a team proposal)
  VFM --> (UC 006 - Register a vehicle)
  VFM --> (UC 007 - Register a vehicle’s check-up)
  VFM --> (UC 008 - List vehicles needing check-up)
}

@enduml