@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "HRM" as USER

participant ":RegisterMaintenanceUI" as RegisterMaintenanceUI
participant ":RegisterMaintenanceController" as RegisterMaintenanceController
participant "Repositories" as Repositories
participant "repositories\n:Repositories" as repRep
participant "VehicleRepository" as VehicleRepository

activate USER
USER -> RegisterMaintenanceUI : Requeste to schedule maintenance
activate RegisterMaintenanceUI
RegisterMaintenanceUI -> RegisterMaintenanceController** : Create
RegisterMaintenanceUI -> USER : requests maintenance data
deactivate RegisterMaintenanceUI
USER -> RegisterMaintenanceUI : Types maintenance details (plate,kms,date)
activate RegisterMaintenanceUI
RegisterMaintenanceUI -> RegisterMaintenanceUI : Keeps and stores that data
RegisterMaintenanceUI -> USER : Shows the typed data and a confirmation requests
deactivate RegisterMaintenanceUI
USER -> RegisterMaintenanceUI : Confirms the data
activate RegisterMaintenanceUI
RegisterMaintenanceUI -> RegisterMaintenanceController : RegisterMaintenance()
activate RegisterMaintenanceController
RegisterMaintenanceController -> Repositories : getInstance()
activate Repositories
Repositories -> RegisterMaintenanceController : Repositories
deactivate Repositories
RegisterMaintenanceController -> repRep : getVehicleRepository()
activate repRep
repRep -> RegisterMaintenanceController : VehicleRepository
deactivate repRep
RegisterMaintenanceController -> VehicleRepository: RegisterMaintenance(plate,kms,date)
activate VehicleRepository
VehicleRepository -> Vehicle** : RegisterMaintenance(plate,kms,date)
VehicleRepository -> VehicleRepository : Save maintenance
VehicleRepository -> RegisterMaintenanceController : maintenance
deactivate VehicleRepository
RegisterMaintenanceController -> RegisterMaintenanceUI : vehicle
deactivate RegisterMaintenanceController
RegisterMaintenanceUI -> USER : Shows the registered vehicle
deactivate RegisterMaintenanceUI


@enduml

