@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AssignSkillsController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillRepository:\nSkillRepository" as SkillRepository
participant "collaboratorRepository:\nCollaboratorRepository" as CollaboratorRepository
participant "collaborator\n:Collaborator" as Collaborator

autonumber 16
-> CTRL : assignSkill(collaboratorIdNumber)

autonumber 16.1

activate CTRL
    group Assign Skill(s)
        CTRL -> CTRL : getSelectedSkillsList()
            activate CTRL

            CTRL -> SkillRepository : getSelectedSkillsList()
            activate SkillRepository

            SkillRepository --> CTRL : selectedSkillsList
            deactivate SkillRepository
            deactivate CTRL

                CTRL -> CTRL : getCollaboratorByIdNumber(collaboratorIdNumber)
                            activate CTRL

                                CTRL -> RepositorySingleton : getInstance()
                                activate RepositorySingleton

                                    RepositorySingleton --> CTRL: repositories
                                deactivate RepositorySingleton

                                CTRL -> PLAT : getCollaboratorRepository()
                                activate PLAT

                                    PLAT -> CTRL : collaboratorRepository
                                deactivate PLAT

                                CTRL -> CollaboratorRepository : getCollaboratorByIdNumber(collaboratorIdNumber)
                                activate CollaboratorRepository

                                loop while false

                                    CollaboratorRepository -> Collaborator : sameIdNumber(collaboratorIdNumber)
                                    activate Collaborator

                                        Collaborator --> CollaboratorRepository : true/false
                                        deactivate Collaborator

                                end loop

                                    CollaboratorRepository --> CTRL : collaborator
                                deactivate CollaboratorRepository
                                    CTRL --> CTRL : collaborator
                            deactivate CTRL

                        CTRL -> RepositorySingleton : getInstance()
                        activate RepositorySingleton

                        RepositorySingleton --> CTRL: repositories
                        deactivate RepositorySingleton

                        CTRL -> PLAT : getCollaboratorRepository()
                        activate PLAT

                        PLAT --> CTRL: collaboratorRepository
                        deactivate PLAT

                        CTRL -> CollaboratorRepository : assignSkill(collaborator, selectedSkillsList)
                        activate CollaboratorRepository

                        CollaboratorRepository -> Collaborator: assignSkill(collaborator, skillsSelectedList)
                        activate Collaborator

                        Collaborator --> CollaboratorRepository : collaborator
                        deactivate Collaborator

                        CollaboratorRepository --> CTRL : collaborator
                        deactivate CollaboratorRepository



    end group

    autonumber 17
    <-- CTRL : collaborator

deactivate CTRL


@enduml