@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AssignSkillsController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillRepository:\nSkillRepository" as SkillRepository

autonumber 13
-> CTRL : getSkillsList()

autonumber 13.1

activate CTRL
    group Get Skills
           CTRL -> RepositorySingleton : getInstance()
           activate RepositorySingleton

           RepositorySingleton --> CTRL: repositories
           deactivate RepositorySingleton

           CTRL -> PLAT : getSkillRepository()
           activate PLAT

           PLAT --> CTRL: skillRepository
           deactivate PLAT

           CTRL -> SkillRepository : getSkills()
           activate SkillRepository

           SkillRepository --> CTRL : skillsList
           deactivate SkillRepository

end group

@enduml