@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":AssignSkillsController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "collaboratorRepository:\nCollaboratorRepository" as CollaboratorRepository

autonumber 3
-> CTRL : getCollaborators()

autonumber 3.1

activate CTRL
    group Get Collaborators
           CTRL -> RepositorySingleton : getInstance()
           activate RepositorySingleton

           RepositorySingleton --> CTRL: repositories
           deactivate RepositorySingleton

           CTRL -> PLAT : getCollaboratorRepository()
           activate PLAT

           PLAT --> CTRL: collaboratorRepository
           deactivate PLAT

           CTRL -> CollaboratorRepository : getCollaborators()
           activate CollaboratorRepository

           CollaboratorRepository --> CTRL : collaboratorsList
           deactivate CollaboratorRepository

end group
autonumber 4
<-- CTRL : collaboratorsList

@enduml