@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US004 - Assign one or more skills to a collaborator

autonumber

actor "HRM" as Employee
participant ":AssignSkillsUI" as UI
participant ":AssignSkillsController" as CTRL
participant "skillRepository:\nSkillRepository" as SkillRepository
participant "selectedSkillsList\nList<Skill>" as selectedSkillsList

activate Employee

    Employee -> UI : asks to assign skill(s) to a collaborator
    activate UI

    UI -> CTRL** : create

                UI -> CTRL : getCollaborators()
                activate CTRL

                    ref over CTRL
                        Get Collaborators
                    end

                    CTRL --> UI : collaboratorsList
                deactivate CTRL

    UI --> Employee : shows list with all collaborators
    deactivate UI

    Employee -> UI : selects the collaborator
    activate UI

        UI -> CTRL : getSkills()
        activate CTRL

            ref over CTRL
                Get Skills
            end

            CTRL --> UI : skillsList
        deactivate CTRL

    loop while HRM wants to continue
    UI --> Employee : shows skills list and requests to select one
    deactivate UI

    Employee -> UI : selects one skill
    activate UI

    UI -> CTRL : addSelectedSkill(skillName)
    activate CTRL

        ref over CTRL
          Add Selected Skill
        end

    UI --> Employee : asks to continue

    deactivate CTRL

    deactivate UI

    Employee -> UI : responds yes or no
    activate UI
    end

    UI --> Employee : shows skill(s) selected and requests confirmation

    deactivate UI

    Employee -> UI : confirms data
    activate UI

    UI -> CTRL : assignSkill(collaboratorIdNumber)
    activate CTRL

    ref over CTRL
        Assign Skill(s)
    end

    CTRL --> UI : collaborator

    deactivate CTRL

    UI --> Employee : displays operation success
    deactivate UI

deactivate Employee
@enduml