@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber 11

participant ":GenerateTeamController" as CTRL
participant "skillRepository:\nSkillRepository" as SkillRepository
participant "selectedSkillsList\nList<Skill>" as selectedSkillsList

-> CTRL : addSelectedSkillName(skillName)
        autonumber 11.1
        group Create Selected Skills List

        activate CTRL

            CTRL -> SkillRepository: addSelectedSkill(skillName)
            activate SkillRepository

                SkillRepository -> SkillRepository: getSkillByName(skillName)
                activate SkillRepository

                SkillRepository --> SkillRepository: skill
                deactivate SkillRepository

                SkillRepository -> selectedSkillsList : add(skill)
                activate selectedSkillsList

                deactivate selectedSkillsList

                deactivate SkillRepository

                end group

            deactivate CTRL
@enduml