@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US 029

autonumber

actor "Collaborator" as Employee
participant ":System" as System

activate Employee

    Employee -> System: selects "Record the completion of a task" option
    activate System

         System --> Employee: asks to choose a skill
            deactivate System
                Employee -> System: chooses skill from list
                    activate System
                       System --> Employee: asks for confirmation of completion of task
                                deactivate System
                                                Employee -> System: validates new task status
                                                    activate System
                                                                           System --> Employee: shows operation success
                                                                                    deactivate System
@enduml