@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US 001

autonumber

actor "HRM" as HRM
participant ":System" as System

activate HRM

    HRM -> System: selects "create skill" option
    activate System

         System --> HRM: request skill name
            deactivate System
                HRM -> System: enters skill name
                    activate System
                       System --> HRM: asks for validation of skill
                                deactivate System
                                                HRM -> System: validates skill
                                                    activate System
                                                                           System --> HRM: shows operation success
                                                                                    deactivate System
@enduml